version: '3'

services:
  mba-web:
    image: httpd:2.4
    ports:
      - "82:80"
    volumes:
      - mba-html:/usr/local/apache2/htdocs
    networks:
      - npm_public

volumes:
  mba-html:
    external: true

networks:
  npm_public:
    external: true